apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-shop-01
  namespace: miztiik-automation-ns
  labels:
    owner: miztiik-automation
    project: eks-security-with-network-policies
    app: k-shop-01
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      owner: miztiik-automation
      project: eks-security-with-network-policies
      app: k-shop-01
  template:
    metadata:
      labels:
        owner: miztiik-automation
        project: eks-security-with-network-policies
        app: k-shop-01
    spec:
      containers:
        # - name: k-shop-nginx
        #   image: nginx:latest
        #   ports:
        #     - name: http
        #       containerPort: 80
        - name: k-shop-busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          command: [ "sh", "-c", "sleep 1h" ]