apiVersion: v1
kind: Pod
metadata:
  name: k-shop-writer
  namespace: miztiik-automation-ns
  labels:
    project: eks-persistent-storage-with-efs
    app: k-shop-writer
    role: writer
spec:
  containers:
  - name: k-shop-writer
    image: busybox
    command: ["/bin/sh"]    
    args: ["-c", "while true; do echo miztiik engineering from: $POD_NAME.$POD_NAMESPACE - $(date -u) >> /shared/out.txt; sleep 5; done"]
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeMounts:
    - name: persistent-storage
      mountPath: /shared
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-storage-claim